### ISSUE TITLE
Implement resetpassword API

### ISSUE THREAD

**Issue by Varyn9** [VarynInc/varyn#1]
Implementation functions for Forgot Password and Reset Password.
- [x] Enginesis.php API
- [x] Enginesis.js API
- [x] Enginesis service API
- [x] Enginesis email #93 (security change)

**Comment by varyndev** [comment]
`RegisteredUserRequestPasswordChange` must be called by a logged in user. It does basically the same thing a `RegisteredUserForgotPassword` does - once validated, it generates a password key (i.e. SecondaryPassword) then sends an email with a link back to /procs/resetpass.php with the user identify and the password key. If the password key matches the form accepts a new password.

Creating a new password then automatically logs in the user and generates a new login token.

**Comment by varyndev** [comment]
updated to two APIs, `RegisteredUserRequestPasswordChange` for the authenticated user changing his password, and `RegisteredUserRequestPasswordChangeUnauth` when the user is not logged in. Since this API is used by both change password and forgot password, we needed the unauth version for forgot password flow. I'm not sure we are going to stick with this but we need something working now to move forward.

**Comment by varyndev** [comment]
BUG: Change Password button on profile.php/Edit/Security should show info popup "An email has been sent to your account to initiate the password reset process.", Then go to profile.php.

**Comment by varyndev** [comment]
BUG: reset password form is not working!
http://www.varyn.com/procs/resetpass.php?id=10090&e=1e6&s=106&u=10244&t=295ff3671c0d4ca8e67c587b25623e5288b30b3f

* does not accept password for enabling button
* Show/Hide does not work

**Comment by varyndev** [comment]
reset password form now working
 * accepts password
 * validates password rule
 * Show/Hide ok
 * removed retype password
