### ISSUE TITLE
In UserLoginCoreg avoid user_name clash

### ISSUE THREAD

**Issue by varyndev** [VarynInc/varyn#146]
SSO services may support duplicate names, but I think we force `user_name` to be unique. If SSO registration and the `user_name` is already taken, we should add some random salt to the name.

could just add a ` + ' ' + increment;` to the user name. But in SQL need to add a loop to check until we find an available name.

**Comment by DarkMatters** [comment]
The code for this is going to be best done inside the stored procedure for `UserLoginCoreg` or `UserCreateCoReg` because

 - must work across the entire platform
 - every site should use the same algorithm
 - a site client code could decide action to take if name clashed (user_name returnd <> userName provided)
 - reduces network transactions (loops to try to see if name selected is available)

Therefore let's create a function to generate a unique user name from a given user name

**Comment by DarkMatters** [comment]
new sql function `fUniqueUserName(site_id, user_name, counter)`

**Comment by varyndev** [comment]
We have to save the original name along with the modified name. If the user re-authenticates with the service, they will appear to have changed their name.

* Login in with site-user-id, check if existing user
* if we have it, see if original name matches current name. if so, continue with no change
* if name changes (or new user), generate new user-name with `fUniqueUserName(site_id, new_user_name, counter)`

**Comment by DarkMatters** [comment]
new column in `users` and `users_deleted` table:

```
alter table users add column site_user_name varchar(50) null after site_user_id;
```

**Comment by DarkMatters** [comment]
updated procedures `fUniqueUserName`, `UserCreateCoreg`, 'UserLoginCoreg`
