### ISSUE TITLE
Enginesis message queue

### ISSUE THREAD

**Issue by DarkMatters** [VarynInc/varyn#234]
In order to have the game work properly while offline (PWA), Enginesis client-side should check if online, if not then queue the requests and process the queue when back online.

**Comment by varyndev** [comment]
Message queue has been added and it was tested.

- Messages are processed in order
- if offline, messages are queued
- when online is restored, messages are sent in order to server. next message is processed after current resolves.
- Promise is resolved when all messages are complete

What is missing is a way to detect we are offline and then when online is restored. Placeholder functions `setOffline` and `restoreOnline` were added but they are not called.
