### ISSUE TITLE
Research using Let's Encrypt CA services

### ISSUE THREAD

**Issue by varyndev** [VarynInc/varyn#246]
Read https://letsencrypt.org/getting-started/

Let’s Encrypt is a free, automated, and open certificate authority (CA), run for the public’s benefit. It is a service provided by the Internet Security Research Group (ISRG).

https://letsencrypt.org/about/

https://scotthelme.co.uk/why-we-need-to-do-more-to-reduce-certificate-lifetimes/

**Comment by DarkMatters** [comment]
It turns out we cannot use this procedure for -l/localhost. Certbot will attempt a DNS lookup and verify the website with the DNS owner, which won't work for localhost. Instead, the -l's will have to be done with a self-signed cert and then security exceptioned with the browser.

On macOS follow https://letsencrypt.org/docs/certificates-for-localhost/

```
openssl req -x509 -out localhost.crt -keyout localhost.key \
  -newkey rsa:2048 -nodes -sha256 \
  -subj '/CN=localhost' -extensions EXT -config <( \
   printf "[dn]\nCN=localhost\n[req]\ndistinguished_name = dn\n[EXT]\nsubjectAltName=DNS:localhost\nkeyUsage=digitalSignature\nextendedKeyUsage=serverAuth")
```

I setup a script to generate the certs on macOS. See `/sitedev/bin/makecerts.sh`. You can copy these certs to a folder and setup Apache .conf to access them The same cert will also work on Windows or wherever else needed by apache.

**Comment by DarkMatters** [comment]
certbot is installed on the AWS Ubuntu servers.
