### ISSUE TITLE
User login is not persisted

### ISSUE THREAD

**Issue by varyndev** [VarynInc/varyn#308]
Log in from game and website should be coordinated and persisted.

Log in via varyn/profile.

- [x] After logging in, go to another page, notice the user is no longer logged in.
- [x] After logging in, go to a game, notice user is not logged in with game.

Log in via game

- [x] After logging in, go to another Varyn page, notice the user is no longer logged in.

**Comment by varyndev** [comment]
issue was due to a bug in encrypt and decrypt algorithms

**Comment by varyndev** [comment]
Restoring the session is confusing sitemark. First sitemark is 0, then later it has a value. This logic must use the same `m=` in both cases or the hashes won't agree.

```txt
Loading Inteligencia v1.0.39 with Enginesis v2.4.70 on Win32 en-US, Mouse, iframe, Web scale:1
enginesis.min.js:1 sessionMakeHash from s=106&u=0&d=9072&n=&g=1105&i=&l=0&m=0&k=B3E06F9352AEA898E yields a1f50b02d78001048160abffc3e4b288
enginesis.min.js:1 restoreUserSessionInfo hash does not match. From server: 214751b74064d72c680a8596b5b9c155. Computed here: a1f50b02d78001048160abffc3e4b288
enginesis.min.js:1 enginesis.restoreUserSessionInfo null
enginesis.min.js:1 enginesis.updateGameSessionInfo session_id is 84299168fca46ee891f13cc848eb206c
enginesis.min.js:1 enginesis.saveUserSessionInfo session id is 84299168fca46ee891f13cc848eb206c
enginesis.min.js:1 sessionMakeHash from s=106&u=0&d=9072&n=&g=1105&i=&l=0&m=1776100053&k=B3E06F9352AEA898E yields 214751b74064d72c680a8596b5b9c155
inteligencia.min.js:1 processSessionBeginResult session is very good
```

**Comment by varyndev** [comment]
add debugging to enginesis.js. The authtok is definitely being passed in, so why is it not used? where is it going wrong?

**Comment by DarkMatters** [comment]
Login data is not in-sync between Varyn and Enginesis. we need to reconcile the session storage.

User is logged in at varyn.com, but the game is in an iframe at enginesis.com. The iframe should be using enginesis.varyn.com.

Varyn.com is not saving the Enginesis session data, so fix that so that `engsession` and `engsession_user` are persisted at enginesis.varyn.com.

- change `siteKey` to obfuscate that value (I don't think we should even persist it in storage)
- add a fakie
- use same login storage for both: engsession, engsession_user and refresh token so that PHP and JavaScript SDKs all agree

**Comment by varyndev** [comment]
A few other notes to address:

1. Enginesis PHP SDK saves 3 cookies and they are redundant, so clean this up we do not need all 3:
    * `engrefreshtoken` holds the users login refresh token
    * `engsession` is holding the authtok
    * `engsession_user` holds the response from SessionRefresh, which also has the authtok and refresh token.
2. Enginesis JS SDK saves `engsession_user` in local storage, which holds some subset of the PHP cookie. change this to store exactly the  SessionRefresh response in local storage.
3. if loading the game with only the authtok, and the client does not have matching local storage or cookie, then call SessionRefresh so we can get and save the user data. This will require a change to SessionRefresh to accept just an authtok. Note this could be a security hole, so further thought is required, but for now assume if the client has the token then the client is allowed to know who the user is.

**Comment by DarkMatters** [comment]
Login data is not in-sync between Varyn and Enginesis. we need to reconcile the session storage.

User is logged in at varyn.com, but the game is in an iframe at enginesis.com. The iframe should be using enginesis.varyn.com.

Varyn.com is not saving the Enginesis session data, so fix that so that `engsession` and `engsession_user` are persisted at enginesis.varyn.com.

- change `siteKey` to obfuscate that value (I don't think we should even persist it in storage)
- add a fakie
- use same login storage for both: engsession, engsession_user and refresh token so that PHP and JavaScript SDKs all agree

**Comment by varyndev** [comment]
3 issues to address:

* Fix the empty userInfo object so there are no undefined values

```txt
sessionMakeHash from s=106&u=undefined&d=9079&n=undefined&g=1105&i=&l=undefined&m=0&k=null yields be4bd3857227424eac1205ded4673c18 enginesis.js:1474:25
```

* Why is sessionMakeHash called twice????

```txt
sessionMakeHash from s=106&u=10241&d=9079&n=Arcade&g=1105&i=&l=10&m=0&k=B3E06F9352AEA898E yields e37fb29442e8737589aa6dfd66c8781d 2 enginesis.js:1474:25
updateLoggedInUserInfo hash does not match. From server: c579412a4aadbf47798f1c42a4ccc252. Computed here: e37fb29442e8737589aa6dfd66c8781d enginesis.js:1474:25
sessionMakeGameHash computed e37fb29442e8737589aa6dfd66c8781d
sessionMakeHash from s=106&u=10241&d=9079&n=Arcade&g=1105&i=&l=10&m=0&k=B3E06F9352AEA898E yields e37fb29442e8737589aa6dfd66c8781d enginesis.js:1474:25
```

* somehow cr was overwritten with c579412a4aadbf47798f1c42a4ccc252 when sessionMakeGameHash computed e37fb29442e8737589aa6dfd66c8781d

```txt
sessionMakeHash from s=106&u=10241&d=9079&n=Arcade&g=1105&i=&l=10&m=0&k=B3E06F9352AEA898E yields e37fb29442e8737589aa6dfd66c8781d enginesis.js:1474:25
```

**Comment by varyndev** [comment]
After log in via game, a message must be posted to the PHP page so that it can update the user interface and show that a user is logged in. I think a `postmessage` back to the parent of the iframe.
